version: 2.1

orbs:
  python: circleci/python@1.2
  heroku: circleci/heroku@1.2

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
        environment:
          DATABASE_URI: postgresql://root:password@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:13.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: password

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      # - run:
      #     name: Run pylint
      #     command: pylint openapi_server
      - run:
          name: Run tests
          command: pytest

workflows:
  sample:
    jobs:
      - build-and-test